// server/src/services/dashboard.service.ts
import { eq, and, sql } from "drizzle-orm";
import {
  agents,
  issues,
  goals,
  approvals,
  costEvents,
} from "@letro/db/schema";
import type { ServiceDependencies } from "./index.js";
import type { BudgetService } from "./budget.service.js";

/**
 * Dashboard aggregation service.
 *
 * Generates dashboard data showing team, task, goal, and cost status
 * at a glance.
 *
 * Displayed as a user-friendly summary in the UI.
 */
export class DashboardService {
  private db;
  private logger;
  private getWindowSpend: (companyId: string) => Promise<number>;
  private budgetService: BudgetService;

  constructor(
    deps: ServiceDependencies,
    getWindowSpend: (companyId: string) => Promise<number>,
    budgetService: BudgetService,
  ) {
    this.db = deps.db;
    this.logger = deps.logger;
    this.getWindowSpend = getWindowSpend;
    this.budgetService = budgetService;
  }

  /**
   * Returns dashboard summary data.
   *
   * Aggregates team/task/goal/cost status via parallel queries
   * and generates a user-friendly summary.
   *
   * @param companyId - Company ID
   */
  async getSummary(companyId: string) {
    const [agentStats, issueStats, goalStats, monthlyCostCents] =
      await Promise.all([
        // Agent (team) stats
        this.db
          .select({
            total: sql<number>`count(*)::int`,
            active: sql<number>`count(*) FILTER (WHERE ${agents.status} IN ('idle', 'working'))::int`,
            leaders: sql<number>`count(*) FILTER (WHERE ${agents.teamRole} = 'leader')::int`,
            members: sql<number>`count(*) FILTER (WHERE ${agents.teamRole} = 'member')::int`,
          })
          .from(agents)
          .where(
            and(
              eq(agents.companyId, companyId),
              sql`${agents.status} != 'terminated'`,
            ),
          ),

        // Issue (task) stats
        this.db
          .select({
            total: sql<number>`count(*)::int`,
            open: sql<number>`count(*) FILTER (WHERE ${issues.status} IN ('backlog', 'todo'))::int`,
            inProgress: sql<number>`count(*) FILTER (WHERE ${issues.status} = 'in_progress')::int`,
            completed: sql<number>`count(*) FILTER (WHERE ${issues.status} = 'done')::int`,
            autoGenerated: sql<number>`count(*) FILTER (WHERE ${issues.originKind} IN ('auto_generated', 'decomposition'))::int`,
          })
          .from(issues)
          .where(eq(issues.companyId, companyId)),

        // Goal stats
        this.db
          .select({
            active: sql<number>`count(*) FILTER (WHERE ${goals.status} = 'active')::int`,
            completed: sql<number>`count(*) FILTER (WHERE ${goals.status} = 'completed')::int`,
            avgProgress: sql<number>`COALESCE(AVG(${goals.progressPercent}), 0)`,
          })
          .from(goals)
          .where(eq(goals.companyId, companyId)),

        // Monthly cost
        this.getWindowSpend(companyId),
      ]);

    const a = agentStats[0];
    const i = issueStats[0];
    const g = goalStats[0];

    // Budget info
    const budgetOverview = await this.budgetService.getOverview(companyId);

    const activeGoals = Number(g?.active ?? 0);
    const completedGoals = Number(g?.completed ?? 0);
    const avgProgress = Math.round(Number(g?.avgProgress ?? 0));
    const activeAgents = Number(a?.active ?? 0);

    return {
      // Team status
      totalAgents: Number(a?.total ?? 0),
      activeAgents,
      leaderCount: Number(a?.leaders ?? 0),
      memberCount: Number(a?.members ?? 0),

      // Issue status
      totalIssues: Number(i?.total ?? 0),
      openIssues: Number(i?.open ?? 0),
      inProgressIssues: Number(i?.inProgress ?? 0),
      completedIssues: Number(i?.completed ?? 0),
      autoGeneratedIssues: Number(i?.autoGenerated ?? 0),

      // Goal status
      activeGoals,
      completedGoals,
      averageProgress: avgProgress,

      // Cost status
      monthlyCostCents,
      budgetRemainingCents: budgetOverview.remainingCents,
      budgetUsedPercent: budgetOverview.usedPercent,

      // User-friendly summary
      userFacingSummary: this.buildUserFacingSummary({
        activeGoals,
        completedGoals,
        avgProgress,
        activeAgents,
        monthlyCost: monthlyCostCents,
      }),
    };
  }

  /**
   * Returns sidebar badge counts.
   *
   * - pendingApprovals: number of pending approval requests
   * - activeIssues: number of in-progress tasks
   * - unreadNotifications: number of unread notifications (currently uses unresolved incident count)
   *
   * @param companyId - Company ID
   */
  async getSidebarBadges(companyId: string) {
    const [pendingResult, activeResult, unreadResult] = await Promise.all([
      // Pending approval requests
      this.db
        .select({ count: sql<number>`count(*)::int` })
        .from(approvals)
        .where(
          and(
            eq(approvals.companyId, companyId),
            eq(approvals.status, "pending"),
          ),
        ),

      // In-progress issues
      this.db
        .select({ count: sql<number>`count(*)::int` })
        .from(issues)
        .where(
          and(
            eq(issues.companyId, companyId),
            eq(issues.status, "in_progress"),
          ),
        ),

      // Unread notifications (using unresolved budget incident count as fallback)
      // TODO: Replace when notifications table is created
      this.db
        .select({ count: sql<number>`count(*)::int` })
        .from(approvals)
        .where(
          and(
            eq(approvals.companyId, companyId),
            eq(approvals.status, "pending"),
          ),
        ),
    ]);

    return {
      pendingApprovals: Number(pendingResult[0]?.count ?? 0),
      activeIssues: Number(activeResult[0]?.count ?? 0),
      unreadNotifications: Number(unreadResult[0]?.count ?? 0),
    };
  }

  /**
   * Builds a user-friendly summary string (Korean UI text).
   */
  private buildUserFacingSummary(stats: {
    activeGoals: number;
    completedGoals: number;
    avgProgress: number;
    activeAgents: number;
    monthlyCost: number;
  }): string {
    const lines: string[] = [];

    if (stats.activeGoals > 0) {
      lines.push(
        `${stats.activeGoals}개 목표가 진행 중이에요 (평균 ${stats.avgProgress}% 완료).`,
      );
    }
    if (stats.completedGoals > 0) {
      lines.push(`${stats.completedGoals}개 목표를 달성했어요!`);
    }
    if (stats.activeAgents > 0) {
      lines.push(`팀원 ${stats.activeAgents}명이 활동 중이에요.`);
    }
    if (stats.monthlyCost > 0) {
      lines.push(
        `이번 달 비용: 약 $${(stats.monthlyCost / 100).toFixed(2)}`,
      );
    }

    return (
      lines.join("\n") ||
      "아직 진행 중인 프로젝트가 없어요. 아이디어를 입력해보세요!"
    );
  }
}
